In [1]:
# Import Libraries for use
import pickle
import pandas as pd
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb
import numpy as np
import os 
import glob
from sklearn.feature_selection import VarianceThreshold
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [2]:
# this is the path to your pickle file (should be the same location as CSVs)
# this path has been changed for GitHub purposes
path = r'..FINAL'

In [9]:
# the below function verifies that the dataframe you are working with is the same shape as the anticipated dataframe
def test_dataframe_shape():
    # load the dataframe to be tested
    with open(f'{path}/working_df2.pkl', 'rb') as file:
        df = pickle.load(file)
    # Perform the shape validation
   # assert df.shape == (27572, 31)
    return df

In [10]:
df = test_dataframe_shape().reset_index(drop=True)

In [11]:
df.head()

Heading(mag)  Vert. Speed  Compass Heading  Roll Rate  Pitch Rate  \
0      39.5754  -104.846953          5888.74       0.02     260.843   
1      39.5754  -104.846953          5888.75       0.03     260.815   
2      39.5754  -104.846953          5888.76       0.04     260.782   
3      39.5754  -104.846953          5888.77       0.05     260.740   
4      39.5754  -104.846953          5888.77       0.05     260.686   

   Pitch Path  Heading Path  Flight Path Angle - VV-[0]  \
0     268.755         0.550                       0.077   
1     268.728         0.519                       0.122   
2     268.695         0.480                       0.166   
3     268.652         0.425                       0.211   
4     268.599         0.351                       0.241   

   Ground Track - VV-[0]  Roll Acceleration  ...  Swashplate Phase  \
0                268.658            -18.613  ...               1.0   
1                268.631            -18.616  ...               1.0   
2                268.598            -15.897  ...               1.0   
3                268.555            -11.346  ...               1.0   
4                268.502             -8.163  ...               1.0   

   GPS 1 DME Distance  GPS 1 DME Speed  NAV 1 DME Time  NAV 1 DME Speed  \
0                 1.0          356.080         260.854          260.854   
1                 1.0          354.501         260.829          260.829   
2                 1.0          352.893         260.799          260.799   
3                 1.0          350.959         260.761          260.761   
4                 1.0          348.617         260.713          260.713   

   NAV 2 NAV ID  GPS Hor Deviation  Label  Dynamic Rollover  LOW-G  
0         2.521             -1.577    NaN                 0      0  
1         2.716             -1.995    NaN                 0      0  
2         2.537             -2.341    NaN                 0      0  
3         1.964             -2.674    NaN                 0      0  
4         0.885             -2.934    NaN                 0      0  

[5 rows x 32 columns]

In [80]:
# Check the data types
#Check the data types
print(df.dtypes.value_counts())
print(df.shape)

float64    28
object      2
int64       2
dtype: int64
(258905, 32)


In [13]:
#Change the NaN in the labels to 'Other'
df['Label'] = df['Label'].fillna('Other')

In [14]:
df.head()

Heading(mag)  Vert. Speed  Compass Heading  Roll Rate  Pitch Rate  \
0      39.5754  -104.846953          5888.74       0.02     260.843   
1      39.5754  -104.846953          5888.75       0.03     260.815   
2      39.5754  -104.846953          5888.76       0.04     260.782   
3      39.5754  -104.846953          5888.77       0.05     260.740   
4      39.5754  -104.846953          5888.77       0.05     260.686   

   Pitch Path  Heading Path  Flight Path Angle - VV-[0]  \
0     268.755         0.550                       0.077   
1     268.728         0.519                       0.122   
2     268.695         0.480                       0.166   
3     268.652         0.425                       0.211   
4     268.599         0.351                       0.241   

   Ground Track - VV-[0]  Roll Acceleration  ...  Swashplate Phase  \
0                268.658            -18.613  ...               1.0   
1                268.631            -18.616  ...               1.0   
2                268.598            -15.897  ...               1.0   
3                268.555            -11.346  ...               1.0   
4                268.502             -8.163  ...               1.0   

   GPS 1 DME Distance  GPS 1 DME Speed  NAV 1 DME Time  NAV 1 DME Speed  \
0                 1.0          356.080         260.854          260.854   
1                 1.0          354.501         260.829          260.829   
2                 1.0          352.893         260.799          260.799   
3                 1.0          350.959         260.761          260.761   
4                 1.0          348.617         260.713          260.713   

   NAV 2 NAV ID  GPS Hor Deviation  Label  Dynamic Rollover  LOW-G  
0         2.521             -1.577  Other                 0      0  
1         2.716             -1.995  Other                 0      0  
2         2.537             -2.341  Other                 0      0  
3         1.964             -2.674  Other                 0      0  
4         0.885             -2.934  Other                 0      0  

[5 rows x 32 columns]

In [15]:
# Create a clustering dataframe where it does not contain the encoding
df_clustering = df.drop(columns=['Dynamic Rollover', 'LOW-G'])

In [16]:
# Next create a test train split on the data

X = df_clustering.drop(['Label'], axis=1)
Y = df_clustering['Label']

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.20)

In [17]:
# Standarize Numerical data
scaler = StandardScaler()
# apply standardization to the data
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [18]:
# Apply a kernel PCA to to the data to reduce the dimensionality
# This was too computationally expensive
# from sklearn.decomposition import KernelPCA
# from sklearn.manifold import TSNE

In [19]:
# tsne = TSNE(n_components=2, random_state=1)

In [20]:
# X_tsne = tsne.fit_transform(X_train)

In [21]:
# Apply a kNN clustering alogrithm to the data

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [22]:
# Make prediction on the data
y_pred = classifier.predict(X_test)

In [23]:
# check the performance of the model
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[  493     0     3]
 [    0   340     0]
 [    3     1 50941]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.99      0.99      0.99       496
           LOW-G       1.00      1.00      1.00       340
           Other       1.00      1.00      1.00     50945

        accuracy                           1.00     51781
       macro avg       1.00      1.00      1.00     51781
    weighted avg       1.00      1.00      1.00     51781



In [24]:
# Create another model with k = 10
classifier2 = KNeighborsClassifier(n_neighbors=10)
classifier2.fit(X_train, y_train)


KNeighborsClassifier(n_neighbors=10)

In [25]:
y_pred2 = classifier2.predict(X_test)

In [26]:
print(confusion_matrix(y_test, y_pred2))
print(classification_report(y_test, y_pred2))

[[  489     0     7]
 [    0   339     1]
 [    3     2 50940]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.99      0.99      0.99       496
           LOW-G       0.99      1.00      1.00       340
           Other       1.00      1.00      1.00     50945

        accuracy                           1.00     51781
       macro avg       1.00      0.99      1.00     51781
    weighted avg       1.00      1.00      1.00     51781



In [27]:
# Create another model with k = 15
classifier3 = KNeighborsClassifier(n_neighbors=15)
classifier3.fit(X_train, y_train)
y_pred3 = classifier3.predict(X_test)

In [28]:
print(confusion_matrix(y_test, y_pred3))
print(classification_report(y_test, y_pred3))

[[  486     0    10]
 [    0   337     3]
 [    3     3 50939]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.99      0.98      0.99       496
           LOW-G       0.99      0.99      0.99       340
           Other       1.00      1.00      1.00     50945

        accuracy                           1.00     51781
       macro avg       0.99      0.99      0.99     51781
    weighted avg       1.00      1.00      1.00     51781



In [29]:
# Create another model with k = 3

classifier4 = KNeighborsClassifier(n_neighbors=3)
classifier4.fit(X_train, y_train)
y_pred4 = classifier4.predict(X_test)

In [30]:
print(confusion_matrix(y_test, y_pred4))
print(classification_report(y_test, y_pred4))

[[  493     0     3]
 [    0   340     0]
 [    3     0 50942]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.99      0.99      0.99       496
           LOW-G       1.00      1.00      1.00       340
           Other       1.00      1.00      1.00     50945

        accuracy                           1.00     51781
       macro avg       1.00      1.00      1.00     51781
    weighted avg       1.00      1.00      1.00     51781



In [31]:
# Next I will apply undersampling to the data to account for the imbalance
import imblearn
from imblearn.under_sampling import RandomUnderSampler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

In [32]:
# Create the split using the under sampling method
# First apply stratification
X_train_us, X_test_us, y_train_us, y_test_us = train_test_split(X, Y, test_size=0.20,
                                                                stratify=Y, random_state=42)

In [33]:
# Next apply the undersampling technique on the training set
rus = RandomUnderSampler(random_state=42)
x_resampled_dr, y_resampled_dr = rus.fit_resample(X_train_us, y_train_us)


In [34]:
# Run the KNN classifier
# k=3
from sklearn.neighbors import KNeighborsClassifier
classifier_us1 = KNeighborsClassifier(n_neighbors=3)
classifier_us1.fit(x_resampled_dr, y_resampled_dr)


KNeighborsClassifier(n_neighbors=3)

In [35]:
y_pred_us = classifier_us1.predict(X_test_us)

In [36]:
# check the performance of the model
print(confusion_matrix(y_test_us, y_pred_us))
print(classification_report(y_test_us, y_pred_us))

[[  511     0     0]
 [    0   344     0]
 [  571   814 49541]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.47      1.00      0.64       511
           LOW-G       0.30      1.00      0.46       344
           Other       1.00      0.97      0.99     50926

        accuracy                           0.97     51781
       macro avg       0.59      0.99      0.70     51781
    weighted avg       0.99      0.97      0.98     51781



In [38]:
# Run the KNN classifier
# k=5
classifier_us2 = KNeighborsClassifier(n_neighbors=5)
classifier_us2.fit(x_resampled_dr, y_resampled_dr)
y_pred_us2 = classifier_us2.predict(X_test_us)

In [39]:
# check the performance of the model
print(confusion_matrix(y_test_us, y_pred_us2))
print(classification_report(y_test_us, y_pred_us2))

[[  511     0     0]
 [    0   344     0]
 [  764  1135 49027]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.40      1.00      0.57       511
           LOW-G       0.23      1.00      0.38       344
           Other       1.00      0.96      0.98     50926

        accuracy                           0.96     51781
       macro avg       0.54      0.99      0.64     51781
    weighted avg       0.99      0.96      0.97     51781



In [40]:
# Run the KNN classifier
# k=10
classifier_us3 = KNeighborsClassifier(n_neighbors=10)
classifier_us3.fit(x_resampled_dr, y_resampled_dr)
y_pred_us3 = classifier_us3.predict(X_test_us)

In [41]:
# check the performance of the model
print(confusion_matrix(y_test_us, y_pred_us3))
print(classification_report(y_test_us, y_pred_us3))

[[  511     0     0]
 [    0   344     0]
 [ 1598  1869 47459]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.24      1.00      0.39       511
           LOW-G       0.16      1.00      0.27       344
           Other       1.00      0.93      0.96     50926

        accuracy                           0.93     51781
       macro avg       0.47      0.98      0.54     51781
    weighted avg       0.99      0.93      0.95     51781



In [42]:
# Run the KNN classifier
# k=15
classifier_us4 = KNeighborsClassifier(n_neighbors=15)
classifier_us4.fit(x_resampled_dr, y_resampled_dr)
y_pred_us4 = classifier_us4.predict(X_test_us)

In [43]:
# check the performance of the model
print(confusion_matrix(y_test_us, y_pred_us4))
print(classification_report(y_test_us, y_pred_us4))

[[  511     0     0]
 [    0   344     0]
 [ 2018  2249 46659]]
                  precision    recall  f1-score   support

Dynamic Rollover       0.20      1.00      0.34       511
           LOW-G       0.13      1.00      0.23       344
           Other       1.00      0.92      0.96     50926

        accuracy                           0.92     51781
       macro avg       0.44      0.97      0.51     51781
    weighted avg       0.99      0.92      0.95     51781



In [52]:
# Perform a grid search for the KNN model
from sklearn.metrics import f1_score, make_scorer
from sklearn.model_selection import GridSearchCV
# Create a ne model to run KNN on
KNN1 = KNeighborsClassifier()
# create the parameter grid with k ranging from 1 to 20
param_grid = {'n_neighbors' : np.arange(1,20)}
# Run the grid search
KNN1_gscv = GridSearchCV(KNN1, param_grid, cv=5, scoring = 'f1_micro')

In [57]:
#Fit the model to the data
#Will use the undersampled data

KNN1_gscv.fit(x_resampled_dr, y_resampled_dr)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])},
             scoring='f1_micro')

In [58]:
# The resulting optimal number of neighbors is 1. However 2 neighbor is 
print(KNN1_gscv.best_params_)

{'n_neighbors': 1}

In [59]:
#The model with n set to 1 had an accuracy of 99% which is likely due to the low bias and high variance
print(KNN1_gscv.best_score_)

0.9937113344712796


In [60]:
# Now a model will be built for only Dynamic Rollover

x_dr = df.drop(columns=['LOW-G', 'Label'])
y_dr = df['Dynamic Rollover']

In [61]:
# Create the split using the under sampling method
# First apply stratification
X_train_dr, X_test_dr, y_train_dr, y_test_dr = train_test_split(x_dr, y_dr, test_size=0.20,
                                                                stratify=y_dr, random_state=42)

In [63]:
# Apply scaling to the training set
scaler.fit(X_train_dr)
X_train_dr = scaler.transform(X_train_dr)
X_test_dr = scaler.transform(X_test_dr)

In [64]:
# Next apply the undersampling technique on the training set
rus = RandomUnderSampler(random_state=42)
x_sampled_dr, y_sampled_dr = rus.fit_resample(X_train_dr, y_train_dr)

In [66]:
# Now run a KNN model with n = 3
classifier_DR1 = KNeighborsClassifier(n_neighbors=3)
classifier_DR1.fit(x_sampled_dr, y_sampled_dr)
y_pred_DR1 = classifier_DR1.predict(X_test_dr)
# check the performance of the model
print(confusion_matrix(y_test_dr, y_pred_DR1))
print(classification_report(y_test_dr, y_pred_DR1))

[[51258    12]
 [    0   511]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51270
           1       0.98      1.00      0.99       511

    accuracy                           1.00     51781
   macro avg       0.99      1.00      0.99     51781
weighted avg       1.00      1.00      1.00     51781



In [67]:
# Now run a KNN model with n = 5
classifier_DR2 = KNeighborsClassifier(n_neighbors=5)
classifier_DR2.fit(x_sampled_dr, y_sampled_dr)
y_pred_DR2 = classifier_DR2.predict(X_test_dr)
# check the performance of the model
print(confusion_matrix(y_test_dr, y_pred_DR2))
print(classification_report(y_test_dr, y_pred_DR2))

[[51251    19]
 [    0   511]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51270
           1       0.96      1.00      0.98       511

    accuracy                           1.00     51781
   macro avg       0.98      1.00      0.99     51781
weighted avg       1.00      1.00      1.00     51781



In [68]:
# Now run a KNN model with n = 10
classifier_DR3 = KNeighborsClassifier(n_neighbors=10)
classifier_DR3.fit(x_sampled_dr, y_sampled_dr)
y_pred_DR3 = classifier_DR3.predict(X_test_dr)
# check the performance of the model
print(confusion_matrix(y_test_dr, y_pred_DR3))
print(classification_report(y_test_dr, y_pred_DR3))

[[51228    42]
 [    0   511]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51270
           1       0.92      1.00      0.96       511

    accuracy                           1.00     51781
   macro avg       0.96      1.00      0.98     51781
weighted avg       1.00      1.00      1.00     51781



In [69]:
# Now run a KNN model with n = 15
classifier_DR4 = KNeighborsClassifier(n_neighbors=15)
classifier_DR4.fit(x_sampled_dr, y_sampled_dr)
y_pred_DR4 = classifier_DR4.predict(X_test_dr)
# check the performance of the model
print(confusion_matrix(y_test_dr, y_pred_DR4))
print(classification_report(y_test_dr, y_pred_DR4))

[[51217    53]
 [    0   511]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51270
           1       0.91      1.00      0.95       511

    accuracy                           1.00     51781
   macro avg       0.95      1.00      0.98     51781
weighted avg       1.00      1.00      1.00     51781



In [70]:
# Create a model for LOW-G only
x_lg = df.drop(columns=['Dynamic Rollover', 'Label'])
y_lg = df['LOW-G']


In [71]:
# Create the split using the under sampling method
# First apply stratification
X_train_lg, X_test_lg, y_train_lg, y_test_lg = train_test_split(x_lg, y_lg, test_size=0.20,
                                                                stratify=y_lg, random_state=42)

In [72]:
# Apply scaling to the training set
scaler.fit(X_train_lg)
X_train_lg = scaler.transform(X_train_lg)
X_test_lg = scaler.transform(X_test_lg)

In [73]:
# Next apply the undersampling technique on the training set
rus = RandomUnderSampler(random_state=42)
x_sampled_lg, y_sampled_lg = rus.fit_resample(X_train_lg, y_train_lg)

In [74]:
# Now run a KNN model with n = 3
classifier_LG1 = KNeighborsClassifier(n_neighbors=3)
classifier_LG1.fit(x_sampled_lg, y_sampled_lg)
y_pred_LG1 = classifier_LG1.predict(X_test_lg)
# check the performance of the model
print(confusion_matrix(y_test_lg, y_pred_LG1))
print(classification_report(y_test_lg, y_pred_LG1))

[[51437     0]
 [    0   344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51437
           1       1.00      1.00      1.00       344

    accuracy                           1.00     51781
   macro avg       1.00      1.00      1.00     51781
weighted avg       1.00      1.00      1.00     51781



In [75]:
# Now run a KNN model with n = 5
classifier_LG2 = KNeighborsClassifier(n_neighbors=5)
classifier_LG2.fit(x_sampled_lg, y_sampled_lg)
y_pred_LG2 = classifier_LG2.predict(X_test_lg)
# check the performance of the model
print(confusion_matrix(y_test_lg, y_pred_LG2))
print(classification_report(y_test_lg, y_pred_LG2))

[[51437     0]
 [    0   344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51437
           1       1.00      1.00      1.00       344

    accuracy                           1.00     51781
   macro avg       1.00      1.00      1.00     51781
weighted avg       1.00      1.00      1.00     51781



In [76]:
# Now run a KNN model with n = 10
classifier_LG3 = KNeighborsClassifier(n_neighbors=10)
classifier_LG3.fit(x_sampled_lg, y_sampled_lg)
y_pred_LG3 = classifier_LG3.predict(X_test_lg)
# check the performance of the model
print(confusion_matrix(y_test_lg, y_pred_LG3))
print(classification_report(y_test_lg, y_pred_LG3))

[[51437     0]
 [    0   344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51437
           1       1.00      1.00      1.00       344

    accuracy                           1.00     51781
   macro avg       1.00      1.00      1.00     51781
weighted avg       1.00      1.00      1.00     51781



In [77]:
# Now run a KNN model with n = 15
classifier_LG4 = KNeighborsClassifier(n_neighbors=15)
classifier_LG4.fit(x_sampled_lg, y_sampled_lg)
y_pred_LG4 = classifier_LG4.predict(X_test_lg)
# check the performance of the model
print(confusion_matrix(y_test_lg, y_pred_LG4))
print(classification_report(y_test_lg, y_pred_LG4))

[[51437     0]
 [    0   344]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     51437
           1       1.00      1.00      1.00       344

    accuracy                           1.00     51781
   macro avg       1.00      1.00      1.00     51781
weighted avg       1.00      1.00      1.00     51781

